# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12e074a8f4ab73aa08b534778a4e5de17eb7647c96e5902d44a6fc6eda41df073c20e3243094925708168e9f91a39fedb74ef6958eafd52b1d3971551586572a

test:
  secret_key_base: 87e378085b599d1d307c4dbba2726f2af0fe14058d277acb4973ecdc9df92f8003bc9ed7e3db2d56f305a3486ff9340896bff1b6a326a1a4253620641c6b009c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
